services:
  mb-postgres:
    image: postgres:15
    container_name: metabase-postgres
    environment:
      POSTGRES_DB: ${MB_POSTGRESQL_DB}
      POSTGRES_USER: ${MB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MB_POSTGRES_PASSWORD}
    volumes:
      - mb-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
    - analytics

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_POSTGRESQL_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${MB_POSTGRES_USER}
      MB_DB_PASS: ${MB_POSTGRES_PASSWORD}
      MB_DB_HOST: mb-postgres
    depends_on:
      - mb-postgres
    restart: unless-stopped
    networks:
    - analytics

volumes:
  mb-postgres-data: